# Where things are
source              : ./src
destination         : ./_site

theme: minima

plugins: [jekyll-scholar]

scholar:
  style: harvard-cite-them-right
  sort_by: author,year
  bibtex_filters:
    - latex
    - markdown